version: "3"
services:
  nginx:
    restart: always
    image: "abdekwant/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  api:
    image: "abdekwant/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    image: "abdekwant/multi-client"
    mem_limit: 128m
    hostname: client
  worker:
    image: "abdekwant/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    