name: Deploy Application
on:
  push:
    branches:
      - master
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build client test suite
        run: docker build -t abdekwant/client-test -f ./client/Dockerfile.dev ./client
        
      - name: Run client test suite
        run: docker run -e CI=true abdekwant/client-test npm test

      - name: Build client image
        run: docker build -t abdekwant/multi-client ./client
        
      - name: Build nginx image
        run: docker build -t abdekwant/multi-nginx ./nginx

      - name: Build server image
        run: docker build -t abdekwant/multi-server ./server

      - name: Build worker image
        run: docker build -t abdekwant/multi-worker ./worker

      - run: docker push abdekwant/multi-client
      - run: docker push abdekwant/multi-nginx
      - run: docker push abdekwant/multi-server
      - run: docker push abdekwant/multi-worker